### ISSUE TITLE
add browser tests

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/couchdb-calculate-session-id#10]
follow up for https://github.com/hoodiehq/couchdb-calculate-session-id/pull/9 @marten-de-vries 

We usually use [zuul](https://www.npmjs.com/package/zuul) and have a helper module with config presets: https://github.com/hoodiehq/hoodie-zuul-config.

Then add two scripts to `package.json`

``` js
    "test:browser:local": "zuul --local 8080 -- tests",
    "test:browser:cloud": "zuul -- tests",
```

and add a test matrix to `.travis.yml`

``` yml
script: npm run $COMMAND
env:
  matrix:
  - COMMAND=test
  - COMMAND=test:browser:cloud
```

I already configured saucelabs credentials on travis
